import React from "react";
import Head from "next/head";
import Navigation from "./Navigation";
import Footer from "./Footer";

const Wrapper = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="Pokemon-app" content="Generated by Binnaz Akyüz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-blue-900 text-5xl text-blue-200 text-center mt-5 pt-6 mb-10">
        <h1> {title} </h1>
        <Navigation />
      </div>

      <main className="container mx-auto">{children}</main>

      <Footer />
    </div>
  );
};

export default Wrapper;
