import React from "react";
import Head from "next/head";
import Navigation from "./Navigation";
import Footer from "./Footer";

const Wrapper = ({ children, title, header}) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="Pokemon-app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className="bg-blue-900 text-5xl text-blue-200 text-center mt-5 py-3">{title}</h1>
      <Navigation />

      <main className="container mx-auto">{children}</main>

      <Footer />
    </div>
  );
};

export default Wrapper;
